$(arg gripper_name)hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - $(arg gripper_name)bl_to_slider1
    - $(arg gripper_name)bl_to_slider2
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      $(arg gripper_name)bl_to_slider1: {trajectory: 0.1, goal: 0.1}
      $(arg gripper_name)bl_to_slider2: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  stopped: true


$(arg gripper_name)hand_group_pos_controller:
  type: position_controllers/JointGroupPositionController
  joints:
      - $(arg gripper_name)bl_to_slider1
      - $(arg gripper_name)bl_to_slider2

