controller_list:
  - name: ur_right/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ur_right_shoulder_pan_joint
      - ur_right_shoulder_lift_joint
      - ur_right_elbow_joint
      - ur_right_wrist_1_joint
      - ur_right_wrist_2_joint
      - ur_right_wrist_3_joint
  - name: ur_right/hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ur_right_bl_to_leftFinger
      - ur_right_leftFinger_to_rightFinger
  - name: ur_left/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ur_left_shoulder_pan_joint
      - ur_left_shoulder_lift_joint
      - ur_left_elbow_joint
      - ur_left_wrist_1_joint
      - ur_left_wrist_2_joint
      - ur_left_wrist_3_joint
  - name: ur_left/hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ur_left_bl_to_leftFinger
      - ur_left_leftFinger_to_rightFinger