ur_right/arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur_right_shoulder_pan_joint
    - ur_right_shoulder_lift_joint
    - ur_right_elbow_joint
    - ur_right_wrist_1_joint
    - ur_right_wrist_2_joint
    - ur_right_wrist_3_joint
ur_right/hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur_right_bl_to_leftFinger
    - ur_right_leftFinger_to_rightFinger
ur_left/arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur_left_shoulder_pan_joint
    - ur_left_shoulder_lift_joint
    - ur_left_elbow_joint
    - ur_left_wrist_1_joint
    - ur_left_wrist_2_joint
    - ur_left_wrist_3_joint
ur_left/hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur_left_bl_to_leftFinger
    - ur_left_leftFinger_to_rightFinger
